### ISSUE TITLE
Errors encountered during setup

### ISSUE THREAD

**Issue by flackbash** [mjstrobl/WEXEA#14]
Dear Michael,

Thank you for making the code to WEXEA public!

I encountered a few minor problems while following the steps in the README to setup WEXEA. I'll outline them here along with my fixes in case anyone else needs it (and for personal reference).

1) Tensorflow 2.4 cannot be installed anymore (using pip). I installed Tensorflow 2.8.4 instead, which conflicts with the specified protobuf version (3.6.0), so I'm using protobuf 3.9.2.

2) When running `parser_3.py`,  I get the error `No module named stanza`. stanza should probably be added to the requirements.

3) Also when running `parser_3.py`, I get the error 

        sutime_path = config['sutime']
        KeyError: 'sutime'

    I added the path to the sutime directory within the WEXEA repository to `configs/config.json`.

**Comment by flackbash** [comment]
When trying to run `parser_4.py, ` I'm encountering the following error: 

```
2024-10-09 11:40:20.630443: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcuda.so.1'; dlerror: libcuda.so.1: cannot open shared object file: No such file or directory
2024-10-09 11:40:20.630463: W tensorflow/stream_executor/cuda/cuda_driver.cc:269] failed call to cuInit: UNKNOWN ERROR (303)
2024-10-09 11:40:20.630482: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:156] kernel driver does not appear to be running on this host (wolga): /proc/driver/nvidia/version does not exist
2024-10-09 11:40:20.630665: I tensorflow/core/platform/cpu_feature_guard.cc:151] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
Traceback (most recent call last):
  File "/local/data/prangen/src/wexea-new-code/env/lib/python3.10/site-packages/tensorflow/python/training/py_checkpoint_reader.py", line 92, in NewCheckpointReader
    return CheckpointReader(compat.as_bytes(filepattern))
RuntimeError: Unsuccessful TensorSliceReader constructor: Failed to find any matching files for 

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/local/data/prangen/src/wexea-new-code/src/parser_4.py", line 329, in <module>
    for var_name, _ in tf.train.list_variables(checkpoint_dir):
  File "/local/data/prangen/src/wexea-new-code/env/lib/python3.10/site-packages/tensorflow/python/training/checkpoint_utils.py", line 109, in list_variables
    reader = load_checkpoint(ckpt_dir_or_file)
  File "/local/data/prangen/src/wexea-new-code/env/lib/python3.10/site-packages/tensorflow/python/training/checkpoint_utils.py", line 64, in load_checkpoint
    return py_checkpoint_reader.NewCheckpointReader(filename)
  File "/local/data/prangen/src/wexea-new-code/env/lib/python3.10/site-packages/tensorflow/python/training/py_checkpoint_reader.py", line 96, in NewCheckpointReader
    error_translator(e)
  File "/local/data/prangen/src/wexea-new-code/env/lib/python3.10/site-packages/tensorflow/python/training/py_checkpoint_reader.py", line 31, in error_translator
    raise errors_impl.NotFoundError(None, None, error_message)
tensorflow.python.framework.errors_impl.NotFoundError: Unsuccessful TensorSliceReader constructor: Failed to find any matching files for
```
From the code it looks like I need to set "original_el_model" in `configs/config.json`, however, I don't know which path this should point to. For now, I'm therefore stuck with using `parser_4_greedy.py`.

Any help with this is appreciated!

**Comment by ido-co** [comment]
Hey @flackbash, Did you manage to run parser 4? I am running into the same issue.
Also, do you have a working requirements file?

**Comment by flackbash** [comment]
Hey @ido-co, I made a working fork with some minor adjustments (for details you can check the last 5 commits) here:
https://github.com/ad-freiburg/WEXEA
The requirements file should work there, but I didn't get parser 4 to run, so I'm only using parser_4_greedy (it does not have a big impact on the results, I ran an evaluation). 
If you have more questions, let me know!
